# Generated by Django 3.2.25 on 2024-07-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240714_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orignal_bag',
            new_name='original_bag',
        ),
    ]
